CREATE TABLE TIMSS.DUES_CARD_MASTER_HISTORY
(
  CUSTOMER        VARCHAR2(8 BYTE),
  FILE_NAME       VARCHAR2(250 BYTE),
  STORAGE_OPTION  VARCHAR2(10 BYTE),
  ADDDATE         DATE,
  ADDOPER         VARCHAR2(12 BYTE)
);

CREATE OR REPLACE PUBLIC SYNONYM DUES_CARD_MASTER FOR TIMSS.DUES_CARD_MASTER_HISTORY;

GRANT DELETE, INSERT, SELECT, UPDATE ON TIMSS.DUES_CARD_MASTER TO TIMSSUSER;
