// <auto-generated />
namespace UniteHere.eMemberRegAppWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Eighth9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eighth9));
        
        string IMigrationMetadata.Id
        {
            get { return "201805011741053_Eighth9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
